kind: Deployment
apiVersion: apps/v1
metadata:
  name: generate-time-statistic-report-scheduler-deployment
  namespace: bms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generate-time-statistic-report-scheduler-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: generate-time-statistic-report-scheduler-deployment
    spec:
      containers:
        - name: generate-time-statistic-report
          image: 741328073657.dkr.ecr.ap-northeast-2.amazonaws.com/bms:{TAG}
          imagePullPolicy: Always
          command: [ "pm2-runtime" ]
          args: [ "start", "./pm2-processes/production.json", "--only", "generate-time-statistic-report-scheduler" ]
          volumeMounts:
            - name: log
              mountPath: /var/log/bms
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.1"
              memory: "100Mi"

      volumes:
        - name: log
          hostPath:
            path: /var/log/bms/production
            type: DirectoryOrCreate

      nodeSelector:
        app: bms
        env: production
