apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: bms
data:
  filebeat.yml: |-
    filebeat.prospectors:
    - type: log
      paths:
        - /root/.pm2/logs/*.log
      tail_files: true
      exclude_files: ['__']
    output.logstash:
      hosts: ["logstash-service.bms.svc.cluster.local:5044"]
      protocol: "tcp"

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-daemonset
  namespace: bms
spec:
  selector:
    matchLabels:
      app: filebeat-daemonset
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: filebeat-daemonset
    spec:
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:6.2.4
          args: [
              "-c", "/opt/filebeat/filebeat.yml",
              "-e",
          ]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /opt/filebeat/
            - name: log
              mountPath: /root/.pm2/logs
      volumes:
        - name: config
          configMap:
            name: filebeat-config
            items:
              - key: filebeat.yml
                path: filebeat.yml
        - name: log
          hostPath:
            path: /var/log/bms/production
            type: DirectoryOrCreate

      nodeSelector:
        app: bms
        env: production
