---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  namespace: bms
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false

    # 1. 啟用 System 模組 (監控 Node 的 CPU/RAM)
    metricbeat.modules:
    - module: system
      enabled: false

    # 2. 啟用 Kubernetes 模組 (監控 Pod/Container)
    - module: kubernetes
      metricsets:
        - pod
        - container
      period: 30s
      host: ${NODE_NAME}
      hosts: ["https://${NODE_NAME}:10250"]
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      ssl.verification_mode: "none"

      processors:
        - drop_event:
            when:
              not:
                and:
                  - equals:
                      kubernetes.namespace: "bms"
                  - regexp:
                      kubernetes.pod.name: "^(bms-management-deployment|bms-platform-deployment)"
        - drop_fields:
            fields:
              - ecs
              - agent
              - host
              - event
              - service
              - kubernetes.annotations
            ignore_missing: true

    # 3. 輸出到 AWS Elasticsearch 
    output.elasticsearch:
      hosts: ["https://search-my-log-rmifnrne3xtana44qq6nmihswu.ap-northeast-2.es.amazonaws.com:443"]
      protocol: "https"
      index: "metricbeat-7.10.2-%{+YYYY.MM.dd}"
      username: "ljit-developer"
      password: "123qweASD?"
      ssl.enabled: true

    setup.ilm.enabled: false
    setup.template.name: "metricbeat"
    setup.template.pattern: "metricbeat-*"
    setup.ilm.check_exists: false  # 禁止檢查 ILM 是否存在
    setup.xpack.security.enabled: false # 禁止檢查 X-Pack 安全功能
    setup.template.settings:
      index.number_of_shards: 1
      index.codec: best_compression

---
# 權限設定 (RBAC) - Metricbeat 需要權限讀取 K8s API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: bms
  labels:
    k8s-app: metricbeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
  labels:
    k8s-app: metricbeat
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - nodes/stats
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: bms
roleRef:
  kind: ClusterRole
  name: metricbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metricbeat
  namespace: bms
  labels:
    k8s-app: metricbeat
spec:
  selector:
    matchLabels:
      k8s-app: metricbeat
  template:
    metadata:
      labels:
        k8s-app: metricbeat
    spec:
      serviceAccountName: metricbeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true 
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat-oss:7.10.2
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          subPath: metricbeat.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: metricbeat-config
      
      nodeSelector:
        app: bms
        env: production
